### ISSUE TITLE
Problems building GUFW (Fedora 35)

### ISSUE THREAD

**Issue by psychedelic-fox** [rpmsphere/noarch#1]
hello, I'm sort of new to Fedora (not Linux in general), so excuse me if this is a stupid issue.

I have RPMFusion and RPMSphere installed and ready to go. both work installing UFW (via `# dnf install ufw`). however, I cannot seem to get GUFW, its graphical interface, to install. upon running `# dnf install gufw`, I am thrown this error:

```
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.9 needed by gufw-21.04.0-1.noarch
(try to add '--skip-broken' to skip uninstallable packages)
```

I have installed Python 3.9 via the `python39` dnf package, however it refuses to install regardless. what am I missing?

**Comment by bluebat** [comment]
You may rebuild it:
> dnf install rpm-build
> dnf builddep https://github.com/rpmsphere/source/raw/master/g/gufw-21.04.0-1.src.rpm
> rpmbuild --rebuild https://github.com/rpmsphere/source/raw/master/g/gufw-21.04.0-1.src.rpm
> rpm -Uvh $HOME/rpmbuild/RPMS/noarch/gufw-21.04.0-1.noarch.rpm

**Comment by psychedelic-fox** [comment]
upon running `gufw`:

```
python3: can't open file '/usr/share/gufw/gufw/gufw.py': [Errno 2] No such file or directory
```

**Comment by bluebat** [comment]
sed -i 's|share/gufw|lib/python3.10/site-packages|' /usr/bin/gufw-pkexec
