### ISSUE TITLE
plastex unable to open images

### ISSUE THREAD

**Issue by will-crawford** [rpmsphere/noarch#12]
python-plastex
0.9.3.20120721
`/usr/lib/python2.7/site-packages/plasTeX/Imagers/__init__.py`
missing "`from PIL`" before the imports of `Image` and `ImageChops`.

**Comment by bluebat** [comment]
Please try this update: https://github.com/rpmsphere/noarch/raw/master/p/python3-plastex-2.1-1.noarch.rpm

**Comment by will-crawford** [comment]
I cannot install the update as it has a requirement `python(abi) = 3.8` and I still have python 3.7:

[root@william ~]# dnf repoquery -q -i --requires python3-plastex
/usr/bin/python3
python(abi) = 3.8
python3-pillow

[root@william ~]# dnf repoquery -q -i --provides python3
python(abi) = 3.7
...

**Comment by will-crawford** [comment]
[root@william ~]# dnf install https://github.com/rpmsphere/noarch/raw/master/p/python3-plastex-2.1-1.noarch.rpm
Last metadata expiration check: 1:39:32 ago on Fri 22 May 2020 20:14:16 BST.
python3-plastex-2.1-1.noarch.rpm                                483 kB/s | 799 kB     00:01    
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.8 needed by python3-plastex-2.1-1.noarch
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by bluebat** [comment]
You may rebuild the source rpm:
https://github.com/rpmsphere/source/raw/master/p/python3-plastex-2.1-1.src.rpm
