### ISSUE TITLE
skylendar does not install on Fedora 32

### ISSUE THREAD

**Issue by ufa** [rpmsphere/noarch#13]
Hi,
I'm trying to install Skylendar from rpmsphere, but I got an error:

sudo dnf install skylendar

Error: 
 Problem: conflicting requests
  - nothing provides libqt5-sql-postgresql >= 4.8.5 needed by skylendar-4.1.2nn-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

Is there a way to install it using dnf?

**Comment by bluebat** [comment]
will be fixed with next commit :)

Workaround:
dnf download skylendar
dnf install postgresql-server perl perl-DBD-Pg perl-XML-DOM
rpm -Uvh --nodeps skylendar-4.1.2nn-1.x86_64.rpm

**Comment by ufa** [comment]
thank you
