### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by OmiceyO** [rpmsphere/noarch#16]
So im coming from here : https://fedora.pkgs.org/33/rpm-sphere-x86_64/scrot-0.8-21.x86_64.rpm.html

That said, do i need to clone this repository on my pc and then run : 
rpm -Uvh rpmsphere-release*rpm

and after that: 
dnf install scrot?

**Comment by bluebat** [comment]
You don't need to clone the repository. See https://rpmsphere.github.io/
