### ISSUE TITLE
Fedora 32 Clonezilla broken dependencies

### ISSUE THREAD

**Issue by rcx11** [rpmsphere/noarch#17]
Attempting to install Clonezilla results in the following output:

Error: 
 Problem: conflicting requests
  - nothing provides drbl >= 1.9.0-43 needed by clonezilla-2.3.1-1.noarch
  - nothing provides drbl-partimage >= 0.6.7 needed by clonezilla-2.3.1-1.noarch
  - nothing provides mkswap-uuid needed by clonezilla-2.3.1-1.noarch

Precursory search indicates that no drbl package exists for Fedora 32. The package drbl-partimage should simply be partimage which also doesn't exist for Fedora 32. Finally, it appears that mkswap-uuid may have been absorbed into mkswap as it is an option for that command, and mkswap is provided by util-linux.

**Comment by bluebat** [comment]
clonezilla, drbl, lzma, partimage imported from Mageia.
