### ISSUE TITLE
crash smokinguns

### ISSUE THREAD

**Issue by mastaiza** [rpmsphere/noarch#2]
ioq3 1.36 (git 20170428) [redhat 12.20170428.3] linux-x86_64 Mar  6 2019
SSE instruction set enabled
----- FS_Startup -----
We are looking in the current search path:
/home/mastaiza/.smokinguns/smokinguns
/home/mastaiza/.smokinguns/smokinguns/sg_textures0.pk3 (1018 files)
/home/mastaiza/.smokinguns/smokinguns/sg_sounds.pk3 (278 files)
/home/mastaiza/.smokinguns/smokinguns/sg_pak0.pk3 (803 files)
/home/mastaiza/.smokinguns/smokinguns/sg_maps0.pk3 (161 files)
/home/mastaiza/.smokinguns/smokinguns/joekarimat1.pk3 (178 files)
/home/mastaiza/.smokinguns/smokinguns/alamo1.pk3 (14 files)
/usr/share/smokinguns/smokinguns

----------------------
2452 files in pk3 files
execing default.cfg
com_zoneMegs will be changed upon restarting.
execing q3config.cfg
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
----- Client Initialization -----
Couldn't read q3history.
----- Initializing Renderer ----
Trying to load "renderer_opengl2_x86_64.so" from "."...
Trying to load "renderer_opengl2_x86_64.so" from "/usr/share/smokinguns"...
Loading "renderer_opengl2_x86_64.so" failed
failed:
"Failed loading /usr/share/smokinguns/renderer_opengl2_x86_64.so: /usr/share/smokinguns/renderer_opengl2_x86_64.so: cannot open shared object file: No such file or directory"
Failed to load renderer

**Comment by bluebat** [comment]
Maybe copy /usr/libexec/ioquake3/renderer_opengl1_x86_64.so and /usr/libexec/ioquake3/renderer_opengl2_x86_64.so to /usr/share/smokinguns/ ?

And try to install:
http://widehat.opensuse.org/opensuse/repositories/games/openSUSE_Tumbleweed/noarch/smokin-guns-data-1.1-5.12.noarch.rpm
http://ftp.nluug.nl/pub/os/Linux/distr/pclinuxos/pclinuxos/apt/pclinuxos/64bit/RPMS.x86_64//smokinguns-data-1.1-1pclos2013.noarch.rpm

**Comment by mastaiza** [comment]
ins smokin-guns-1.1-6.95.x86_64.rpm smokin-guns-data-1.1-5.12.noarch.rpm
[sudo] пароль для mastaiza: 
Последняя проверка окончания срока действия метаданных: 2:14:18 назад, Пн 11 мар 2019 18:55:33.
Ошибка: 
 Проблема: conflicting requests
  - nothing provides libjpeg.so.8()(64bit) needed by smokin-guns-1.1-6.95.x86_64
  - nothing provides libjpeg.so.8(LIBJPEG_8.0)(64bit) needed by smokin-guns-1.1-6.95.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

**Comment by mastaiza** [comment]
pclinuxos the game works

**Comment by bluebat** [comment]
dnf install http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/releases/28/Everything/x86_64/os//compat-libjpeg8-1.5.3-3.fc28.x86_64.rpm

**Comment by bluebat** [comment]
smokinguns-data includes binary game data and too big (>100MB) to save in Github.

**Comment by mastaiza** [comment]
after installing compat-libjpeg8 game earned from opensuse

**Comment by bluebat** [comment]
updated to version 1.1
