### ISSUE TITLE
crash ioquake3-demo

### ISSUE THREAD

**Issue by mastaiza** [rpmsphere/noarch#3]
ioq3 1.36 (git 20170428) [redhat 12.20170428.3] linux-x86_64 Mar  6 2019
SSE instruction set enabled
----- FS_Startup -----
We are looking in the current search path:
/home/mastaiza/.q3a/baseq3
/usr/libexec/ioquake3/baseq3

----------------------
0 files in pk3 files
"pak0.pk3" is missing. Please copy it from your legitimate Q3 CDROM. Point Release files are missing. Please re-install the 1.32 point release. Also check that your ioq3 executable is in the correct place and that every file in the "baseq3" directory is present and readable

**Comment by bluebat** [comment]
https://github.com/ioquake/ioq3/issues/292
http://wiki.ioquake3.org/Players_Guide#Installation_3

It seems autodownloader called by ioquake3-update and ioquake3-demo not well configured.

**Comment by bluebat** [comment]
It seems OK now.
