### ISSUE TITLE
zxsd won't start with solarus

### ISSUE THREAD

**Issue by covex** [rpmsphere/noarch#5]
Solarus 1.1.1
Opening quest '/usr/share/solarus/zsxd'
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Fatal: Failed to load quest.dat: [string "quest.dat"]:1: unexpected symbol near '#'
/usr/bin/zsxd: line 2:  3086 Aborted                 (core dumped) solarus /usr/share/solarus/zsxd

the solarus and zsxd packages also seems bit outdated. Nevertheless, distributed versions do not work together.

**Comment by bluebat** [comment]
updated:
https://github.com/rpmsphere/x86_64/raw/master/s/solarus-1.6.5-1.x86_64.rpm
https://github.com/rpmsphere/noarch/raw/master/s/solarus-quest-zsxd-1.12.2-1.noarch.rpm

**Comment by covex** [comment]
Confirming this is running fine.
