### ISSUE TITLE
gpsprune crash

### ISSUE THREAD

**Issue by evoblue** [rpmsphere/noarch#6]
On a fresh install of fedora 30, when starting gpsprune I get the following error:
" Starting gpsprune version 15.1 ...
with options :
Error: impossible to find or load main class tim.prune.GpsPrune"

The error message is localized in my language so this is my translation back to English.
The sphere repo version is 29.2 and  the installation of "gpsprune-15.1-9.1.noarch" works without warnings or problems.
I re-installed but the error is identical all the times.
Suggestions?

**Comment by bluebat** [comment]
Thanks for reporting.
I have bypassed some errors when "gpsprune" was built :(
It needs extra "java3d" package but I cannot build them from source.
So I will make a binary package directly from official .jar file instead.

**Comment by evoblue** [comment]
Thanks for your work, I appreciate it very much.
I hope that your diagnose is correct because this is a very useful package.
I think that starting from the original Jar file can work, unless there
is some virtual machine  mismatch...

**Comment by bluebat** [comment]
New package:
https://github.com/rpmsphere/todo/raw/master/noarch/gpsprune-19.2-1.bin.noarch.rpm
