### ISSUE TITLE
gpsprune crash

### ISSUE THREAD

**Issue by evoblue** [rpmsphere/noarch#7]
On a fedora 30 fresh installation, after installing the new updated version gpsprune-19.2-1.bin.noarch I get the following error:
$ gpsprune 
Starting gpsprune version 19.2 ...
with options :
Exception in thread "main" java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at tim.prune.GpsPrune.launch(Unknown Source)
	at tim.prune.GpsPrune.main(Unknown Source)

I think some library is missing in the jar or in the package requirements.

**Comment by evoblue** [comment]
using X11 instead of wayland did not help

**Comment by evoblue** [comment]
using alternatives to switch java  runtime solved the problem even if it is not clear why.
This is what I did:
$ sudo alternatives --config java

selected : 
java-latest-openjdk.x86_64 (/usr/lib/jvm/java-12-openjdk-12.0.1.12-1.rolling.fc30.x86_64/bin/java)

Now the application works.

Any idea why id doesn't work with the default java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.fc30.x86_64/jre/bin/java) ?

**Comment by bluebat** [comment]
It seems that the official gpsprune.jar was built with java-12-openjdk and not compatible with java-1.8-openjdk.

**Comment by bluebat** [comment]
move to rpmsphere/caution and fix
