### ISSUE TITLE
repo for fedora 31 that doesn't take it from me?

### ISSUE THREAD

**Issue by xzj8b3** [rpmsphere/noarch#9]
but for Fedora 31, a working repo? He doesn't take it from me.

**Comment by bluebat** [comment]
Is there any package with problem in compatibility?

**Comment by xzj8b3** [comment]
> Esiste un pacchetto con problemi di compatibilità?

no the correct repository would need ... translators are not correct!!!!

**Comment by xzj8b3** [comment]
> Is there any package with problem in compatibility?

But to install the correct repo in given rpm didn't it go on 31?

**Comment by xzj8b3** [comment]
> Esiste un pacchetto con problemi di compatibilità?

a m'è in Fedora 31 does not work repository, send me to be able to install it properly!!!

**Comment by bluebat** [comment]
Please try:
dnf install https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-30-1.noarch.rpm

**Comment by xzj8b3** [comment]
> Prova:
> dnf install https://github.com/rpmsphere/noarch/raw/master/r/rpmsphere-release-30-1.noarch.rpm

Take a look at it, because wifite on fedora seems to get bogged down when it scans a network and doesn't go any further!!!! maybe it could be useful for you

**Comment by bluebat** [comment]
Please update wifite and try again.

**Comment by bluebat** [comment]
updated for Fedora 32.
